Platform targets

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -24,23 +24,35 @@ jobs:
         ruby-version: [2.7, '3.0', 3.1, 3.2, 3.3, 3.4, head, debug, truffleruby]
         include:
           - arch_os: aarch64-darwin
-            os: macos-latest
+            os: macos-14
+            gem_platform: arm64-darwin
+          - arch_os: aarch64-darwin
+            os: macos-14
+            gem_platform: arm64-darwin-24
           - arch_os: x86_64-linux
             os: ubuntu-latest
+            gem_platform: x86_64-linux
           # - arch_os: aarch64-linux
           #   os: ubuntu-latest
+          #   gem_platform: aarch64-linux
           # - arch_os: arm-linux
           #   os: ubuntu-latest
+          #   gem_platform: arm-linux
           # - arch_os: i386-linux
           #   os: ubuntu-latest
+          #   gem_platform: i386-linux
           # - arch_os: i686-windows
           #   os: windows-latest
+          #   gem_platform: x86_64-windows
           # - arch_os: riscv64-linux
           #   os: ubuntu-latest
+          #   gem_platform: riscv64-linux
           # - arch_os: x86_64-darwin
           #   os: macos-latest
+          #   gem_platform: x86_64-darwin
           # - arch_os: x86_64-windows
           #   os: windows-latest
+          #   gem_platform: x64-mingw32
     continue-on-error: ${{ endsWith(matrix.ruby-version, 'head') || matrix.ruby-version == 'debug' }}
     runs-on: ${{ matrix.os }}
     steps:
@@ -53,12 +65,14 @@ jobs:
       - name: Build gem for platform
         run: |
           bundle exec rake ethon_impersonate:build[${{ matrix.arch_os }}]
+      - name: Remove ext/libcurl* after build
+        run: rm -rf ext/libcurl*
       - name: Install built gem for platform
         run: |
           version=$(ruby -r ./lib/ethon_impersonate/version.rb -e 'puts EthonImpersonate::VERSION')
-          gem_file=$(ls ethon-impersonate-${version}-*.gem | grep ${{ matrix.arch_os }} | head -n1)
+          gem_file=$(ls ethon-impersonate-${version}-${{ matrix.gem_platform }}.gem | head -n1)
           if [ -z "$gem_file" ]; then
-            echo "Gem file for ${{ matrix.arch_os }} not found!"; exit 1;
+            echo "Gem file for ${{ matrix.gem_platform }} not found!"; exit 1;
           fi
           gem install ./$gem_file --force
       - name: Run tests with built gem
